#
# Makefile generated by an AI assistant.
#

# The 'all' rule is the default goal. It builds both programs.
all: servidor cliente

# --- Rules to build the SERVER ---

# Rule to link the server executable in the root directory.
servidor: obj/server_udp.o
	gcc -Wall -g -pthread obj/server_udp.o -o servidor

# Rule to compile the server source code into an object file.
obj/server_udp.o: src/server_udp.c
	@mkdir -p obj
	gcc -Wall -g -pthread -c src/server_udp.c -o obj/server_udp.o

# --- Rules to build the CLIENT ---

# Rule to link the client executable in the root directory.
cliente: obj/client_udp.o
	gcc -Wall -g -pthread obj/client_udp.o -o cliente

# Rule to compile the client source code into an object file.
obj/client_udp.o: src/client_udp.c
	@mkdir -p obj
	gcc -Wall -g -pthread -c src/client_udp.c -o obj/client_udp.o

# --- Cleanup Rule ---

# Deletes the object directory and the executables from the root.
clean:
	rm -rf obj servidor cliente

# Declares that 'all' and 'clean' are not actual file names.
.PHONY: all clean