#
# Makefile generated by an AI assistant.
#

# The 'all' rule is the default goal. It builds both programs.
all: bin/servidor bin/cliente

# --- Rules to build the SERVER ---

# Rule to link the server executable from its object file.
bin/servidor: obj/server_udp.o
	@mkdir -p bin
	gcc -Wall -g -pthread obj/server_udp.o -o bin/servidor

# Rule to compile the server source code into an object file.
obj/server_udp.o: src/server_udp.c
	@mkdir -p obj
	gcc -Wall -g -pthread -c src/server_udp.c -o obj/server_udp.o

# --- Rules to build the CLIENT ---

# Rule to link the client executable from its object file.
bin/cliente: obj/client_udp.o
	@mkdir -p bin
	gcc -Wall -g -pthread obj/client_udp.o -o bin/cliente

# Rule to compile the client source code into an object file.
obj/client_udp.o: src/client_udp.c
	@mkdir -p obj
	gcc -Wall -g -pthread -c src/client_udp.c -o obj/client_udp.o

# --- Cleanup Rule ---

# Deletes all generated files and directories.
clean:
	rm -rf obj bin

# Declares that 'all' and 'clean' are not actual file names.
.PHONY: all clean